# Generated by Django 4.2.9 on 2025-09-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='choices',
            field=models.JSONField(default=list),
        ),
    ]
