# Generated by Django 4.2.9 on 2025-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grid',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='solution',
            field=models.CharField(max_length=1000),
        ),
    ]
