# Generated by Django 4.2.9 on 2025-10-03 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0002_alter_item_column_alter_item_id_alter_item_row_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column',
            field=models.SmallIntegerField(help_text='Enter a number between 1 and 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='row',
            field=models.SmallIntegerField(help_text='Enter a number between 1 and 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
