# Generated by Django 4.2.9 on 2025-09-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0002_item_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
    ]
