# Generated by Django 4.2.9 on 2025-09-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0003_alter_item_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], max_length=20),
        ),
    ]
