# Generated by Django 4.2.9 on 2025-10-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0003_alter_item_column_alter_item_id_alter_item_row_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='puzzleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_levels', to='create_puzzles.difficulty', to_field='value')),
            ],
        ),
    ]
