# Generated by Django 4.2.9 on 2025-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_puzzles', '0004_alter_item_grid_alter_item_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='grid',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='item',
            name='solution',
            field=models.JSONField(default=dict),
        ),
    ]
